site_name: FCTD AI Governance
docs_dir: site-content

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.emoji
  - attr_list
  - md_in_html
  - pymdownx.snippets    # <— ini penting utk include potongan MD


theme:
  name: material
  features:
    - navigation.expand
    - navigation.sections
    - navigation.top
    - search.suggest
    - content.code.copy
    - toc.integrate

nav:
  - Home: index.md
  - Governance:
    - Principles: governance/principles.md
    - Roles & Responsibilities: governance/roles-and-responsibilities.md
    - Operating Model: governance/operating-model.md
  - Risk:
    - Risk Register: risk/risk-register.md
    - Risks:
      - Hallucination: risk/risks/hallucination.md
      - Data Leakage: risk/risks/data-leakage.md
      - Model Drift: risk/risks/model-drift.md
    - Controls:
      - Prompt Management: risk/controls/prompt-management.md
      - PII Redaction: risk/controls/pii-redaction.md
      - Human-in-the-Loop: risk/controls/human-in-the-loop.md
  - Lifecycle:
    - Ideation: lifecycle/ideation-checklist.md
    - Data Governance: lifecycle/data-governance.md
    - Development: lifecycle/model-development.md
    - Evaluation: lifecycle/evaluation.md
    - Deployment: lifecycle/deployment.md
    - Monitoring: lifecycle/monitoring.md
  - Templates:
    - AI Impact Assessment: templates/ai-impact-assessment.md
    - Model Card: templates/model-card.md
    - Data Sheet: templates/data-sheet.md
    - Red Teaming Report: templates/red-teaming-report.md
  - Examples:
    - AIA (Customer Support RAG): examples/use-cases/customer-support-rag/aia.md
    - Model Card (Customer Support RAG): examples/use-cases/customer-support-rag/model-card.md

