site_name: FCTD AI Governance
docs_dir: site-content

theme:
  name: material
  features:
    - navigation.top
    - navigation.sections
    - search.suggest
    - content.code.copy
    - toc.integrate

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.emoji
  - attr_list
  - md_in_html
  - pymdownx.snippets

nav:
  - Home: index.md
  - Governance:
    - Principles: governance/principles.md
  - Risk:
    - Risk Register: risk/risk-register.md
  - Controls:
    - Prompt Management: controls/prompt-management.md
    - PII Redaction: controls/pii-redaction.md
  - Lifecycle:
    - AI Lifecycle: lifecycle/ai-lifecycle.md
  - Roadmap: roadmap.md
  - References: references.md
  - Research:
    - Framework Diagram: research/research-framework.md
    - AI Toolkit: research/ai-toolkit.md
    - Results: research/results.md

