- name: Set up Python
  uses: actions/setup-python@v5
  with:
    python-version: "3.12"   # pakai 3.12 lebih aman untuk ekosistem mkdocs

- name: Install MkDocs + plugins
  run: |
    python -m pip install --upgrade pip
    pip install \
      mkdocs-material \
      mkdocs-bibtex \
      pymdown-extensions

# ... lalu build dengan path mkdocs yang benar:
- name: Build site
  run: mkdocs build -f docs/mkdocs.yml --site-dir docs/site

- name: Deploy to gh-pages
  uses: peaceiris/actions-gh-pages@v3
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    publish_dir: docs/site
    publish_branch: gh-pages
    force_orphan: true

    - name: Show installed mkdocs packages
  run: pip freeze | grep -i mkdocs || true
