name: Deploy MkDocs (gh-pages)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install MkDocs + plugins (pip)
        run: |
          python -m pip install --upgrade pip
          pip install \
            mkdocs \
            mkdocs-material \
            mkdocs-bibtex \
            pymdown-extensions

      - name: Show versions
        run: |
          mkdocs --version
          python -c "import mkdocs_bibtex, sys; print('mkdocs_bibtex OK:', mkdocs_bibtex.__version__)"

      - name: Build site
        run: mkdocs build -f docs/mkdocs.yml --site-dir docs/site

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/site
          publish_branch: gh-pages
          force_orphan: true
