name: "ci: mkdocs build (docs/mkdocs.yml)"

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '.github/workflows/fctd-governance-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '.github/workflows/fctd-governance-ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install MkDocs + plugins
        run: |
          python -m pip install --upgrade pip
          pip install \
            mkdocs==1.6.1 \
            mkdocs-material \
            mkdocs-material-extensions \
            pymdown-extensions \
            pybtex>=0.24 \
            mkdocs-bibtex==2.13.1

      # OPTIONAL: kalau ada requirements.txt untuk toolkit riset, boleh dipasang:
      # - name: Install project requirements (optional)
      #   run: |
      #     if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Show tree (debug)
        run: |
          echo "::group::Tree docs/"
          ls -la docs
          echo ""
          echo "docs_dir (dari mkdocs.yml) -> site-content, cek ada file:"
          ls -la docs/site-content | head -n 60
          echo "::endgroup::"

      - name: Build MkDocs
        run: |
          # mkdocs.yml dipakai yang ini (sesuai repo kakak)
          mkdocs build -f docs/mkdocs.yml

      # CI ini HANYA build untuk cek – tidak deploy.
      # Deploy ke Pages biarkan job GitHub Pages yang sudah ada (pages-build-deployment) yang menangani.
