name: ci: build & deploy MkDocs (with bibtex)

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '.github/workflows/fctd-governance-ci.yml'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install MkDocs + Material + BibTeX
        run: |
          python -m pip install --upgrade pip
          pip install \
            mkdocs==1.6.1 \
            mkdocs-material \
            mkdocs-bibtex \
            pymdown-extensions

      - name: Sanity check mkdocs_bibtex
        run: |
          python - <<'PY'
          import pkgutil
          print("mkdocs_bibtex installed:", 'mkdocs_bibtex' in [m.name for m in pkgutil.iter_modules()])
          PY

      - name: Build site (docs/mkdocs.yml)
        working-directory: docs
        run: mkdocs build -f mkdocs.yml --strict

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/site
          publish_branch: gh-pages
          force_orphan: true
